{% set name = "narwhals" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/narwhals-{{ version }}.tar.gz
  sha256: a2213fa44a039f724278fb15609889319e7c240403413f2606cc856c8d8f708d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
  run_constrained:
    # See optional dependencies in https://github.com/narwhals-dev/narwhals/blob/main/pyproject.toml
    # Matches MIN_VERSIONS in https://github.com/narwhals-dev/narwhals/blob/main/narwhals/utils.py
    - pandas >=0.25.3
    - modin # See https://github.com/narwhals-dev/narwhals/issues/817 
    - cudf >=24.10.0 # no conda-forge package
    - pyarrow >=11.0.0
    - pyspark >=3.5.0
    - polars >=0.20.3
    - dask-core >=2024.8
    - duckdb >=1.0
    - ibis-framework >=6.0.0
    # no conda package: - sqlframe >=3.22.0

test:
  imports:
    - narwhals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://marcogorelli.github.io/narwhals/
  dev_url: https://github.com/MarcoGorelli/narwhals
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
