schema_version: 1

context:
  name: narwhals
  version: "1.38.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/narwhals-${{ version }}.tar.gz
  sha256: 7c5fbc9f2b8e1d5d95f49dcef9c2d94bf17810de68c87ff195dc7d22f7b3eeb5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - narwhals
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md
  homepage: https://marcogorelli.github.io/narwhals/
  repository: https://github.com/MarcoGorelli/narwhals

extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
