schema_version: 1

context:
  name: narwhals
  version: "2.27.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/narwhals-${{ version }}.tar.gz
  sha256: aed93076a3ea42d9c32c88e4eb5ea422a21937011cbe1f480f9572a523c82094

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.11.0,<0.13.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - narwhals
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md
  homepage: https://narwhals-dev.github.io/narwhals/
  repository: https://github.com/narwhals-dev/narwhals

extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
