conda_build_tool: rattler-build
bot: {automerge: true, inspection: hint-all}
conda_build: {error_overlinking: true}
conda_forge_output_validation: true
github: {branch_name: main, tooling_branch_name: main}
